function Bio(){
    return(
    <div className="text-white">
     
        <h1 className="text-xl font-bold mb-2">Jarred Moyer</h1>

        
        <p className="mb-4">
            Software Engineer at{' '}  
            <a href="http://www.wethehobby.com" target="_blank" className="text-blue-300 hover:underline">
                Topshelf Enterprises
            </a>
        </p>

        
        <p className="mb-4">
            Following my recent graduation from RIT with a B.S. in Software Engineering, I joined Topshelf Enterprises as a full-stack developer. My projects span a broad range, including custom dynamic broadcast elements, inventory management, and product construction. Additionally, I've been instrumental in devising intuitive methods to analyze and interpret the vast amounts of data generated by these projects.
            My journey into programming began as a developer for a First Tech Challenge (FTC) team. Since then, I've delved into full-stack development and explored facets of machine learning all while finding time to occasionally mentor my former FTC team

        </p>

        
        <div className="flex space-x-4">
            <a href="mailto:your@email.com" className="text-blue-500 hover:underline">
                Email
            </a>
            <a href="https://www.linkedin.com/in/your-linkedin-handle/" target="_blank" className="text-blue-500 hover:underline">
                LinkedIn
            </a>
            <a href="https://github.com/your-github-handle" target="_blank" className="text-blue-500 hover:underline">
                GitHub
            </a>
        </div>
    </div>)
}
export default Bio